/* Generated by tools/build-search-index.py - do not edit by hand.
   Re-run that script after changing any page's copy. */
window.SITE_INDEX = [
 {
  "page": "Home",
  "url": "index.html#disciplines",
  "title": "Four ways to break a clay",
  "text": "What you can shoot Four ways to break a clay Every discipline here uses a shotgun and a clay target. What changes is where the target comes from and how much it is trying to fool you. Course Sporting clays Fourteen stations, each a different presentation — long crossers, springing teal, rabbits bouncing along the ground. Walk it or take a cart. Often called golf with a shotgun. Field Trap Targets thrown away from you from a single house, five stations, twenty-five birds to a round. The most forgiving place to start. Field Skeet High house and low house, eight stations, crossing targets at know",
  "tags": [
   "sporting clays",
   "trap",
   "skeet",
   "5-stand",
   "five stand",
   "course",
   "field"
  ]
 },
 {
  "page": "Home",
  "url": "index.html#first-time",
  "title": "Start here, not on YouTube",
  "text": "Never shot clays? Start here, not on YouTube Tell the desk it is your first time. Orientation is free, takes about twenty minutes, and covers gun fit, mount, eye dominance and the range commands. Then a coach walks you onto a station and stays until you are breaking targets. You do not need to own a shotgun, and you do not need to know anything. Bring closed-toe shoes and a hat with a brim — we have everything else. Read the FAQ Range rules What a first visit looks like Sign the waiver at the clubhouse desk — two minutes. Free loaner eye and ear protection, fitted before you walk out. Twenty-m",
  "tags": [
   "beginner",
   "new",
   "never",
   "first",
   "orientation",
   "lesson",
   "coach"
  ]
 },
 {
  "page": "Home",
  "url": "index.html#photos",
  "title": "Ninety acres, thirty-one stations",
  "text": "The property Ninety acres, thirty-one stations Photographs of the course, the fields and the clubhouse go here. Photo 01Sporting course — a station in the treeline Photo 02Trap field at golden hour Photo 03Clubhouse and the gun racks Photo 04Someone breaking a target, mid-shot Photo 05The cart path through the hardwoods Photo 06A squad of four walking the course",
  "tags": [
   "pictures",
   "gallery",
   "images",
   "property"
  ]
 },
 {
  "page": "Rates",
  "url": "rates.html#targets",
  "title": "Targets & equipment",
  "text": "Everything below is per shooter, per visit. Members pay the discounted column. Target prices and rentals ItemPublicMember Sporting clays, 100 targets $70.00 $58.00 Sporting clays, 50 targets $38.00 $32.00 Trap, round of 25 $9.00 $6.00 Skeet, round of 25 $9.00 $6.00 5-Stand, round of 25 $12.00 $9.00 Cart rental, one trip round the course $25.00 $20.00 Shotgun rental, 12 or 20 gauge $20.00 $15.00 Shells, box of 25 $11.00 $10.00 Eye & ear protection, loaner Free Free Youth 17 & under, trap & skeet −50% −50% Prices shown are placeholders for this draft — swap in the club's real numbers before laun",
  "tags": [
   "price",
   "prices",
   "cost",
   "how much",
   "rates",
   "fees",
   "cart",
   "rental"
  ]
 },
 {
  "page": "Rates",
  "url": "rates.html#membership",
  "title": "Memberships",
  "text": "Annual, running twelve months from the day you join rather than to a fixed date. Membership pays for itself at roughly twenty-nine rounds of a hundred sporting targets a year — about every other weekend. Individual $349 / year $12 off every hundred sporting targets $3 off every round of trap or skeet Priority squad times on weekends League entry at member rate Four guest passes a year Family $549 / year · household Everything above, for two adults Dependents under 18 at the youth rate Six guest passes a year Punch card $80 / 10 rounds of 25 No membership needed, never expires Transferable — go",
  "tags": [
   "member",
   "join",
   "annual",
   "dues",
   "punch card",
   "discount"
  ]
 },
 {
  "page": "Rates",
  "url": "rates.html#groups",
  "title": "Groups, leagues & instruction",
  "text": "Corporate outings, fundraisers, bachelor and bachelorette parties, birthdays. We staff the stations, run the scoring and can put an instructor with every squad so nobody stands around confused. Ask about leagues and about instruction for individuals and small groups — both are booked through the clubhouse. Call the clubhouse to book — group pricing depends on head count, target volume and whether you want food. Payment & policies Cash and major cards accepted. No personal checks. Pay at the clubhouse before you go out, not at the station. Unused targets on a hundred-target card carry to your n",
  "tags": [
   "corporate",
   "party",
   "bachelor",
   "birthday",
   "fundraiser",
   "league",
   "lesson",
   "instructor",
   "event",
   "outing",
   "pay",
   "payment",
   "card",
   "credit",
   "cash",
   "check",
   "deposit",
   "refund",
   "policy"
  ]
 },
 {
  "page": "Rules",
  "url": "rules.html#four",
  "title": "The four that never bend",
  "text": "Treat every gun as if it is loaded. Never point the muzzle at anything you are not willing to destroy. Keep your finger off the trigger until you are calling for the target. Know your target and what lies beyond it. If something feels wrong, stop Open the action, put the gun down, and say so. Nobody here will be annoyed with you. A stopped squad costs two minutes; the alternative does not bear thinking about.",
  "tags": [
   "safety",
   "safe",
   "muzzle",
   "trigger",
   "loaded"
  ]
 },
 {
  "page": "Rules",
  "url": "rules.html#house",
  "title": "House rules",
  "text": "Shotguns only. No rifles, no handguns. Actions open and empty everywhere except on the station. Load a maximum of two shells, and only when it is your turn to shoot. Muzzles point up or down — never level, never at a person. Eye and ear protection for everyone on the fields, spectators included. Stay behind the shooting station; stay on the cart paths on the course. No alcohol before or during shooting. None carried on the course. Shooters under 18 must be accompanied by a parent or guardian. Pick up your hulls before you leave the station. Dogs on lead, clubhouse side of the gate only. No sho",
  "tags": [
   "rules",
   "regulations",
   "dogs",
   "alcohol",
   "hulls",
   "spectator"
  ]
 },
 {
  "page": "Rules",
  "url": "rules.html#ammunition",
  "title": "Guns & ammunition",
  "text": "Bring your own or rent ours. Either way, what comes out of the barrel matters more than what it comes out of. Ammunition rules Shot size no larger than #7½. No more than 1⅛ oz of shot per shell. Target loads only — no slugs, no buckshot, no magnum field loads. No steel or other non-toxic shot on the sporting course without asking first. No reloads in rental guns. Factory shells are sold at the clubhouse if you would rather not haul your own. Guns Any shotgun in safe working order — over/under, semi-auto, pump, side-by-side. 12, 20, 28 gauge and .410 all welcome. Rentals are 12 and 20. Guns tra",
  "tags": [
   "shells",
   "shot",
   "gauge",
   "12",
   "20",
   "28",
   "410",
   "steel",
   "lead",
   "slug",
   "buckshot",
   "reload",
   "ammo"
  ]
 },
 {
  "page": "Rules",
  "url": "rules.html#commands",
  "title": "Range commands",
  "text": "Five words do almost all the talking on a clay range. Knowing them makes your first round far less bewildering. What you will hear on the station CallWhat it means Pull The shooter is mounted and ready; the trapper releases the target. Mark Same as pull, used on trap fields and in some clubs. Interchangeable here. No bird The target was broken on launch, thrown wrong, or two came out. It does not count — you get it again. Lost The target was thrown fairly and you missed it. Happens to everyone, constantly. Hold / Cease fire Stop immediately. Unload, open the action, step back from the station ",
  "tags": [
   "pull",
   "mark",
   "lost",
   "no bird",
   "cease fire",
   "terminology",
   "terms"
  ]
 },
 {
  "page": "Rules",
  "url": "rules.html#waiver",
  "title": "Waivers, age & ID",
  "text": "Every shooter signs a liability waiver once per season. It takes about two minutes at the desk, and you can sign it for the whole family at the same time. Shooters under 18 must be accompanied by a parent or legal guardian, who signs on their behalf and stays on the station with them. We ask for photo ID from anyone renting a shotgun. Placeholder — needs legal review The four universal safety rules are standard everywhere. House rules, shot size limits, non-toxic shot requirements and minimum ages vary by club, by property and by state. Have the owner and their insurer review this page and the",
  "tags": [
   "age",
   "minor",
   "kids",
   "children",
   "id",
   "sign",
   "liability",
   "insurance"
  ]
 },
 {
  "page": "Visit",
  "url": "visit.html#hours",
  "title": "Hours",
  "text": "Open weekends, year round Saturday 9:00 AM – 5:00 PM Sunday 9:00 AM – 4:00 PM Monday – Friday Closed",
  "tags": [
   "open",
   "opening",
   "closed",
   "closing",
   "times",
   "schedule",
   "when",
   "holiday"
  ]
 },
 {
  "page": "Visit",
  "url": "visit.html#weather",
  "title": "Weather",
  "text": "We shoot in rain, wind and cold — clays fly fine in all three, and a quiet range on a drizzly morning is one of the better ways to spend it. Lightning closes the fields until thirty minutes after the last strike. High wind can shut individual stations on the course. If the sky looks unsettled, call the clubhouse before you drive out. Call ahead We are open Saturday and Sunday only, so a wasted drive costs a whole weekend. If the forecast looks rough, (205) 821-4879 will tell you in ten seconds whether we are throwing targets.",
  "tags": [
   "rain",
   "lightning",
   "storm",
   "wind",
   "cold",
   "winter",
   "season",
   "dusk",
   "dark"
  ]
 },
 {
  "page": "Visit",
  "url": "visit.html#location",
  "title": "Find us",
  "text": "Address 14931 Seed Town RdFosters, AL 35463 Directions Seed Town Rd, Fosters, about twenty minutes southwest of Tuscaloosa. Parking Free on-site parking.",
  "tags": [
   "address",
   "directions",
   "map",
   "where",
   "parking",
   "drive",
   "find"
  ]
 },
 {
  "page": "Visit",
  "url": "visit.html#contact",
  "title": "Get in touch",
  "text": "Phone (205) 821-4879 Email fisherfarmsshootingventures@gmail.com Groups & bookings Call for corporate outings, parties and fundraisers. Please give us as much notice as you can for larger groups. Instruction Lessons by appointment, individually or in small groups.",
  "tags": [
   "phone",
   "email",
   "call",
   "book",
   "booking",
   "reservation"
  ]
 },
 {
  "page": "Visit",
  "url": "visit.html#firstvisit",
  "title": "Before your first visit",
  "text": "Closed-toe shoes — the course is uneven and often wet. A hat with a brim. Falling chips of clay are harmless but startling. Layers. Open ground runs colder than the parking lot. A vest or a jacket with deep pockets to carry shells. Photo ID if you plan to rent a shotgun. Cash or card — we do not take personal checks. Everything else — gun, shells, eye and ear protection, targets, coaching — is available here. Where the club is MapEmbedded map or static image with a link to directions",
  "tags": [
   "what to bring",
   "wear",
   "shoes",
   "hat",
   "checklist",
   "prepare"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-never-shot",
  "title": "I have never shot clays. Can I just show up?",
  "text": "Yes. Walk in on a Saturday or Sunday, tell the desk it is your first time, and we take it from there. Orientation is free and takes about twenty minutes — gun fit, mount, eye dominance and the range commands — and then an instructor puts you on a station and stays until you are breaking targets. No appointment needed for trap, skeet or 5-stand. If you want the sporting course on a Saturday, call ahead.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-what-to-wear",
  "title": "What should I wear?",
  "text": "Closed-toe shoes, a hat with a brim, and layers. The course is uneven and often wet, falling chips of clay are harmless but startling, and ninety acres of open field runs colder than the parking lot. A vest or a jacket with deep pockets makes carrying shells much easier.",
  "tags": [
   "clothes",
   "clothing",
   "dress",
   "boots"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-own-gun",
  "title": "Do I need my own shotgun?",
  "text": "No. Rentals are $20 for the public and $15 for members, in 12 or 20 gauge. Photo ID required. Shells are $11 a box of twenty-five at the clubhouse.",
  "tags": [
   "borrow",
   "loaner",
   "hire"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-how-long",
  "title": "How long does a round take?",
  "text": "A round of twenty-five at trap or skeet takes twenty to thirty minutes. A hundred targets on the sporting course takes a squad of four about two hours walking, a little less with a cart.",
  "tags": [
   "time",
   "duration",
   "how long"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-spectators",
  "title": "Can I bring someone who is only watching?",
  "text": "Yes, and it costs nothing. Eye and ear protection is required for everyone on the fields, spectators included — we lend both free. Watchers stay behind the shooting station.",
  "tags": [
   "watch",
   "watching",
   "guest",
   "kids watching"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-gauge",
  "title": "What gauge should a beginner shoot?",
  "text": "A 20 gauge is lighter and kicks less, which matters a lot over a hundred targets. A 12 gauge is the most common and gives you the widest choice of shells. We rent both — try a 20 first if you are recoil-shy or small-framed.",
  "tags": [
   "recoil",
   "kick",
   "which gauge"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-own-shells",
  "title": "Can I bring my own shells?",
  "text": "Yes, within the ammunition rules: shot size no larger than #7½, no more than 1⅛ oz per shell, target loads only. No slugs, no buckshot, no magnum field loads. Ask before bringing steel or other non-toxic shot onto the sporting course. Reloads are fine in your own gun but not in a rental.",
  "tags": [
   "ammo",
   "ammunition",
   "bring my own"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-semi-auto",
  "title": "Can I shoot a semi-auto or a pump?",
  "text": "Any shotgun in safe working order is welcome — over/under, semi-auto, pump, side-by-side. The two-shell maximum applies to everyone regardless of what the magazine holds.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-rifles",
  "title": "Do you allow rifles or handguns?",
  "text": "No. This is a clay target club: shotguns only, on every field and every station.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-shot-size",
  "title": "Why does shot size matter?",
  "text": "Shot larger than #7½ carries further than the property's safety fall zones were designed for. It is the single most common reason a shooter gets stopped on a clay range, and it is nothing personal.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-reservation",
  "title": "Do I need a reservation?",
  "text": "Not for trap, skeet or 5-stand — those are walk-on. For the sporting course, groups of six or more should call ahead. Since we are only open Saturday and Sunday, weekend mornings are the busy stretch.",
  "tags": [
   "book",
   "booking",
   "appointment",
   "walk in",
   "walk-in"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-corporate",
  "title": "Can you host a corporate outing or a party?",
  "text": "Yes — corporate outings, fundraisers, bachelor and bachelorette parties, birthdays. We staff the stations, run scoring, and can put an instructor with each squad so nobody stands around confused. Group pricing depends on head count and target volume; call the clubhouse. Deposit and final head count are due seven days out.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-lessons",
  "title": "Do you offer lessons?",
  "text": "NSCA-certified instruction by appointment, individually or in small groups. An hour with an instructor early on will save you a season of grooving in bad habits.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-leagues",
  "title": "Are there leagues?",
  "text": "Call or ask at the desk about current leagues and how to get on the list.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-rain",
  "title": "Do you close when it rains?",
  "text": "No. We shoot in rain, wind and cold. Lightning closes the fields until thirty minutes after the last strike, and high wind can shut individual stations on the course. If the sky looks unsettled, call before you drive out.",
  "tags": [
   "cancel",
   "cancelled",
   "closed"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-winter",
  "title": "Are you open in the winter?",
  "text": "Yes. We keep the same hours year round — Saturday 9:00 AM to 5:00 PM and Sunday 9:00 AM to 4:00 PM. Dress for it and bring gloves; cold does not bother a clay target one bit.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-membership-worth",
  "title": "Is a membership worth it?",
  "text": "Depends how often you shoot. Individual membership is $349 a year and saves $12 on every hundred sporting targets, so it pays for itself at roughly twenty-nine rounds — about every other weekend. If you come three or four times a season, buy the $80 punch card instead: ten rounds of twenty-five, transferable, never expires.",
  "tags": [
   "cost",
   "value",
   "cheaper",
   "save"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-payment",
  "title": "What payment do you take?",
  "text": "Cash and major cards. No personal checks. Pay at the clubhouse before you go out rather than at the station.",
  "tags": [
   "venmo",
   "apple pay",
   "tap"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-age",
  "title": "How old do you have to be?",
  "text": "Shooters under 18 must be accompanied by a parent or legal guardian, who signs the waiver and stays on the station with them. Whether a particular young shooter is ready is a judgement call the instructor makes with the parent — it has more to do with size and attention than birthdays.",
  "tags": [
   "kids",
   "children",
   "minimum age",
   "how old",
   "teenager"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-eye-ear",
  "title": "Do I need to bring eye and ear protection?",
  "text": "No — loaners are free, and fitted at the desk before you walk out. Bring your own if you have a pair you like.",
  "tags": [
   "glasses",
   "muffs",
   "plugs",
   "hearing",
   "protection"
  ]
 }
];
