/* Generated by tools/build-search-index.py - do not edit by hand.
   Re-run that script after changing any page's copy. */
window.SITE_INDEX = [
 {
  "page": "Home",
  "url": "index.html#disciplines",
  "title": "Three stands, one weekend",
  "text": "What you can shoot Three stands, one weekend Same shotgun, same clay target. What changes is where it comes from and how hard it is trying to fool you. The one to try Live Action Duck and dove flight patterns thrown by eight Atlas machines firing multi-directionally, so no two targets come from the same place. Duck runs high, fast, crossing, angled and looping; dove comes low and straight, rising and falling. Unpredictable on purpose — and every pattern is simulated, with no live birds. Stand Trap Targets thrown away from you from a single house. The most forgiving place to start, and the one ",
  "tags": [
   "sporting clays",
   "trap",
   "skeet",
   "5-stand",
   "five stand",
   "course",
   "field"
  ]
 },
 {
  "page": "Home",
  "url": "index.html#first-time",
  "title": "Start here, not on YouTube",
  "text": "Never shot clays? Start here, not on YouTube Tell us at the stand that it is your first time. Somebody will go over gun handling, how the machines throw, and what the station menus mean before you shoot anything. Bring your own shotgun and closed-toe shoes and a hat with a brim. Eye and ear protection is required past the stand — the posted notice is not a suggestion. Shells are for sale at the clubhouse. Read the FAQ Range rules What a first visit looks like Check in at the stand and say it is your first time. Eye and ear protection on before you step up. Action stays open until you are on th",
  "tags": [
   "beginner",
   "new",
   "never",
   "first",
   "orientation",
   "lesson",
   "coach"
  ]
 },
 {
  "page": "Home",
  "url": "index.html#photos",
  "title": "Where you will be standing",
  "text": "The property Where you will be standing Off Seed Town Road in Fosters, twenty-odd minutes southwest of Tuscaloosa. The stand, the tables and somewhere to park the Ranger. Station one, menu posted on the post. Live Action runs weekends only. The pond at the edge of the property.",
  "tags": [
   "pictures",
   "gallery",
   "images",
   "property"
  ]
 },
 {
  "page": "Rates",
  "url": "rates.html#targets",
  "title": "What we shoot",
  "text": "Three stands, all of them weekend-only. Pricing is set at the clubhouse — call and we will tell you exactly what your round costs before you drive out. Stands StandPrice Live Action — duck & dove simulation Call Trap Call Skeet Call Call (205) 821-4879 for current pricing.",
  "tags": [
   "price",
   "prices",
   "cost",
   "how much",
   "rates",
   "fees",
   "cart",
   "rental"
  ]
 },
 {
  "page": "Rates",
  "url": "rates.html#clubhouse",
  "title": "At the clubhouse",
  "text": "Ammunition is sold here, so you do not have to haul a case of shells across the county to shoot a round. Snacks and cold drinks too — an Alabama Saturday on an open field earns both. Check in at the clubhouse before you head out to a stand. Sold on site Ammunition Snacks Cold drinks Bring your own gun We do not rent shotguns, so bring one that works and that fits you. Any shotgun in safe working order is welcome — see the gun and ammunition rules before you load up.",
  "tags": []
 },
 {
  "page": "Rates",
  "url": "rates.html#groups",
  "title": "Groups & events",
  "text": "Bringing a crowd — a company outing, a fundraiser, a birthday, a bachelor party? Call ahead so we can have the stands and the machines ready for you rather than fitting you in around a busy Saturday. Call (205) 821-4879 to talk it through. Before you come Open Saturdays and Sundays only. Bring your own shotgun — there are no rentals. Ammunition, snacks and drinks are available at the clubhouse. Eye and ear protection is required in the shooting area. Cash and card both accepted at the clubhouse. Call ahead if you are bringing a group. We shoot in rain and cold. Lightning closes the stands.",
  "tags": [
   "corporate",
   "party",
   "bachelor",
   "birthday",
   "fundraiser",
   "league",
   "lesson",
   "instructor",
   "event",
   "outing",
   "pay",
   "payment",
   "card",
   "credit",
   "cash",
   "check",
   "deposit",
   "refund",
   "policy"
  ]
 },
 {
  "page": "Rules",
  "url": "rules.html#four",
  "title": "The four that never bend",
  "text": "Treat every gun as if it is loaded. Never point the muzzle at anything you are not willing to destroy. Keep your finger off the trigger until you are calling for the target. Know your target and what lies beyond it. If something feels wrong, stop Open the action, put the gun down, and say so. Nobody here will be annoyed with you. A stopped squad costs two minutes; the alternative does not bear thinking about.",
  "tags": [
   "safety",
   "safe",
   "muzzle",
   "trigger",
   "loaded"
  ]
 },
 {
  "page": "Rules",
  "url": "rules.html#house",
  "title": "House rules",
  "text": "Shotguns only. No rifles, no handguns. Actions open and empty everywhere except on the stand — it is the posted rule here. Load a maximum of two shells, and only when it is your turn to shoot. Muzzles point up or down — never level, never at a person. Eye and ear protection for everyone on the fields, spectators included. Stay behind the stand unless you are the one shooting. No alcohol before or during shooting. Shooters under 18 must be accompanied by a parent or guardian. Pick up your hulls before you leave the station. Dogs on lead, clubhouse side only. No shooting at wildlife, ever, for a",
  "tags": [
   "rules",
   "regulations",
   "dogs",
   "alcohol",
   "hulls",
   "spectator"
  ]
 },
 {
  "page": "Rules",
  "url": "rules.html#ammunition",
  "title": "Guns & ammunition",
  "text": "Bring your own shotgun — there are no rentals here. Ammunition is sold at the clubhouse. What comes out of the barrel matters more than what it comes out of. Ammunition rules Shot size no larger than #7½. No more than 1⅛ oz of shot per shell. Target loads only — no slugs, no buckshot, no magnum field loads. Ask first before bringing steel or other non-toxic shot. Ammunition is sold at the clubhouse if you would rather not haul your own. Guns Any shotgun in safe working order — over/under, semi-auto, pump, side-by-side. 12, 20, 28 gauge and .410 all welcome. Bring your own — we do not rent. Gun",
  "tags": [
   "shells",
   "shot",
   "gauge",
   "12",
   "20",
   "28",
   "410",
   "steel",
   "lead",
   "slug",
   "buckshot",
   "reload",
   "ammo"
  ]
 },
 {
  "page": "Rules",
  "url": "rules.html#commands",
  "title": "Range commands",
  "text": "Five words do almost all the talking on a clay range. Knowing them makes your first round far less bewildering. What you will hear on the station CallWhat it means Pull The shooter is mounted and ready; the trapper releases the target. Mark Same as pull, used more on the trap stand. Interchangeable here. No bird The target was broken on launch, thrown wrong, or two came out. It does not count — you get it again. Lost The target was thrown fairly and you missed it. Happens to everyone, constantly. Hold / Cease fire Stop immediately. Unload, open the action, step back from the stand and wait for",
  "tags": [
   "pull",
   "mark",
   "lost",
   "no bird",
   "cease fire",
   "terminology",
   "terms"
  ]
 },
 {
  "page": "Rules",
  "url": "rules.html#waiver",
  "title": "Waivers, age & ID",
  "text": "Check in at the clubhouse before you head out to a stand. Shooters under 18 must be accompanied by a parent or legal guardian, who stays on the stand with them. Placeholder — needs legal review The four universal safety rules are standard everywhere. House rules, shot size limits, non-toxic shot requirements and minimum ages vary by club, by property and by state. Have the owner and their insurer review this page and the waiver language before it goes live.",
  "tags": [
   "age",
   "minor",
   "kids",
   "children",
   "id",
   "sign",
   "liability",
   "insurance"
  ]
 },
 {
  "page": "Visit",
  "url": "visit.html#hours",
  "title": "Hours",
  "text": "Open weekends, year round Saturday 9:00 AM – 5:00 PM Sunday 9:00 AM – 4:00 PM Monday – Friday Closed",
  "tags": [
   "open",
   "opening",
   "closed",
   "closing",
   "times",
   "schedule",
   "when",
   "holiday"
  ]
 },
 {
  "page": "Visit",
  "url": "visit.html#weather",
  "title": "Weather",
  "text": "We shoot in rain, wind and cold — clays fly fine in all three, and a quiet range on a drizzly morning is one of the better ways to spend it. Lightning closes the stands until thirty minutes after the last strike. If the sky looks unsettled, call the clubhouse before you drive out. Call ahead We are open Saturday and Sunday only, so a wasted drive costs a whole weekend. If the forecast looks rough, (205) 821-4879 will tell you in ten seconds whether we are throwing targets.",
  "tags": [
   "rain",
   "lightning",
   "storm",
   "wind",
   "cold",
   "winter",
   "season",
   "dusk",
   "dark"
  ]
 },
 {
  "page": "Visit",
  "url": "visit.html#location",
  "title": "Find us",
  "text": "Address 14931 Seed Town RdFosters, AL 35463 Directions Seed Town Rd, Fosters, about twenty minutes southwest of Tuscaloosa. Parking Free on-site parking.",
  "tags": [
   "address",
   "directions",
   "map",
   "where",
   "parking",
   "drive",
   "find"
  ]
 },
 {
  "page": "Visit",
  "url": "visit.html#contact",
  "title": "Get in touch",
  "text": "Phone (205) 821-4879 Email fisherfarmsshootingventures@gmail.com Groups & bookings Call for corporate outings, parties and fundraisers. Please give us as much notice as you can for larger groups. Instruction Ask at the clubhouse.",
  "tags": [
   "phone",
   "email",
   "call",
   "book",
   "booking",
   "reservation"
  ]
 },
 {
  "page": "Visit",
  "url": "visit.html#firstvisit",
  "title": "Before your first visit",
  "text": "Closed-toe shoes — the course is uneven and often wet. A hat with a brim. Falling chips of clay are harmless but startling. Layers. Open ground runs colder than the parking lot. A vest or a jacket with deep pockets to carry shells. Your own shotgun — there are no rentals here. Cash or card — both work at the clubhouse. Ammunition, snacks and cold drinks are sold at the clubhouse. Get directions Fisher Farms Shooting Ventures 14931 Seed Town RdFosters, AL 35463 Open in Google Maps Apple Maps",
  "tags": [
   "what to bring",
   "wear",
   "shoes",
   "hat",
   "checklist",
   "prepare"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-never-shot",
  "title": "I have never shot clays. Can I just show up?",
  "text": "Yes. Come on a Saturday or Sunday, check in at the clubhouse and say it is your first time. Somebody will go over gun handling and how the stand works before you shoot anything. Bring your own shotgun — there are no rentals. Trap is the gentlest place to start.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-what-to-wear",
  "title": "What should I wear?",
  "text": "Closed-toe shoes, a hat with a brim, and layers. The course is uneven and often wet, falling chips of clay are harmless but startling, and ninety acres of open field runs colder than the parking lot. A vest or a jacket with deep pockets makes carrying shells much easier.",
  "tags": [
   "clothes",
   "clothing",
   "dress",
   "boots"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-own-gun",
  "title": "Do I need my own shotgun?",
  "text": "Yes. We do not rent shotguns, so bring your own — any shotgun in safe working order, in any common gauge. Ammunition is sold at the clubhouse, so shells are the one thing you can turn up without.",
  "tags": [
   "borrow",
   "loaner",
   "hire"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-how-long",
  "title": "How long does a round take?",
  "text": "A round of twenty-five at trap or skeet takes twenty to thirty minutes. Live Action runs longer because you will want to go again.",
  "tags": [
   "time",
   "duration",
   "how long"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-spectators",
  "title": "Can I bring someone who is only watching?",
  "text": "Yes. Eye and ear protection is required for everyone in the shooting area, spectators included, so bring a spare set. Watchers stay behind the stand.",
  "tags": [
   "watch",
   "watching",
   "guest",
   "kids watching"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-gauge",
  "title": "What gauge should a beginner shoot?",
  "text": "A 20 gauge is lighter and kicks less, which matters over a long morning. A 12 gauge is the most common and gives the widest choice of shells. Since you are bringing your own, borrow a 20 from somebody first if you are recoil-shy or small-framed.",
  "tags": [
   "recoil",
   "kick",
   "which gauge"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-own-shells",
  "title": "Can I bring my own shells?",
  "text": "Yes, within the ammunition rules: target loads only, no slugs, no buckshot, no magnum field loads. Ammunition is also sold at the clubhouse if you would rather not haul your own.",
  "tags": [
   "ammo",
   "ammunition",
   "bring my own"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-semi-auto",
  "title": "Can I shoot a semi-auto or a pump?",
  "text": "Any shotgun in safe working order is welcome — over/under, semi-auto, pump, side-by-side. The two-shell maximum applies to everyone regardless of what the magazine holds.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-rifles",
  "title": "Do you allow rifles or handguns?",
  "text": "No. This is a clay target range: shotguns only, on every stand.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-shot-size",
  "title": "Why does shot size matter?",
  "text": "Shot larger than a target load carries further than a range's safety fall zones are designed for. It is the most common reason a shooter gets stopped on a clay range, and it is nothing personal.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-reservation",
  "title": "Do I need a reservation?",
  "text": "Not for a normal visit — walk on and shoot. Call ahead if you are bringing a group, so the stands and machines are ready for you. Since we are only open Saturday and Sunday, weekend mornings are the busy stretch.",
  "tags": [
   "book",
   "booking",
   "appointment",
   "walk in",
   "walk-in"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-corporate",
  "title": "Can you host a corporate outing or a party?",
  "text": "Yes — corporate outings, fundraisers, bachelor and bachelorette parties, birthdays. We staff the stations, run scoring, and can put an instructor with each squad so nobody stands around confused. Group pricing depends on head count and target volume; call the clubhouse. Deposit and final head count are due seven days out.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-lessons",
  "title": "Do you offer lessons?",
  "text": "Ask at the clubhouse or call (205) 821-4879.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-leagues",
  "title": "Are there leagues?",
  "text": "Call or ask at the desk about current leagues and how to get on the list.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-rain",
  "title": "Do you close when it rains?",
  "text": "No. We shoot in rain, wind and cold. Lightning closes the fields until thirty minutes after the last strike, and high wind can shut individual stations on the course. If the sky looks unsettled, call before you drive out.",
  "tags": [
   "cancel",
   "cancelled",
   "closed"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-winter",
  "title": "Are you open in the winter?",
  "text": "Yes. We keep the same hours year round — Saturday 9:00 AM to 5:00 PM and Sunday 9:00 AM to 4:00 PM. Dress for it and bring gloves; cold does not bother a clay target one bit.",
  "tags": []
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-membership-worth",
  "title": "Do you offer memberships?",
  "text": "Call the clubhouse on (205) 821-4879 and ask — pricing and any membership options are set there.",
  "tags": [
   "cost",
   "value",
   "cheaper",
   "save"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-payment",
  "title": "What payment do you take?",
  "text": "Cash and card are both fine. Pay at the clubhouse before you head out to a stand.",
  "tags": [
   "venmo",
   "apple pay",
   "tap"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-age",
  "title": "How old do you have to be?",
  "text": "Shooters under 18 must be accompanied by a parent or legal guardian, who signs the waiver and stays on the station with them. Whether a particular young shooter is ready is a judgement call the instructor makes with the parent — it has more to do with size and attention than birthdays.",
  "tags": [
   "kids",
   "children",
   "minimum age",
   "how old",
   "teenager"
  ]
 },
 {
  "page": "FAQ",
  "url": "faq.html#faq-eye-ear",
  "title": "Do I need to bring eye and ear protection?",
  "text": "Bring your own. Eye and ear protection is required for everyone in the shooting area, including anyone just watching.",
  "tags": [
   "glasses",
   "muffs",
   "plugs",
   "hearing",
   "protection"
  ]
 }
];
